fix(workflow):indent error

diff --git a/.github/workflows/update-words.yml b/.github/workflows/update-words.yml
--- a/.github/workflows/update-words.yml
+++ b/.github/workflows/update-words.yml
@@ -237,11 +237,12 @@ jobs:
           git push -f origin word-updates || echo "Failed to push changes"
 
       - name: Merge to main on Sunday
-          run: |
-            if [ "$(date -u +'%w')" -eq 1 ]; then
-              git checkout main
-              git merge word-updates || echo "Merge failed, manual intervention needed"
-              git push origin main || echo "Failed to push to main"
-            else
-              echo "Today is not Sunday. Skipping merge."
-            fi
+        if: github.event_name == 'schedule'
+        run: |
+          if [ "$(date -u +'%w')" -eq 1 ]; then
+            git checkout main
+            git merge word-updates || echo "Merge failed, manual intervention needed"
+            git push origin main || echo "Failed to push to main"
+          else
+            echo "Today is not Sunday. Skipping merge."
+          fi
